### ISSUE TITLE
Any plan to open-source it?

### ISSUE THREAD

**Issue by LeoneChen** [purseclab/FuzzSGX#1]
Hello!

Paper "Fuzzing SGX Enclaves via Host Program Mutations" is interesting. Any plan to open-source it?

**Comment by Arslan8** [comment]
Hi @LeoneChen! 
Thanks for your interest in our project. Sorry, I missed your message as I have been busy with other engagements. Anyhow, we have open-sourced the project recently. All components are committed with an example target (wolf-ssl). You can try the project using the example target if you like. I will work on the documentation and readability of the code in the upcoming days. Please feel free to reach out with any questions that you might have. 
Cheers!

**Comment by LeoneChen** [comment]
Thanks! Could you show how to use FuzzSGX in README? It's helpful!
